export interface InvestigatedContentEntity {
  /**
   * Path is the full path to the file or directory
   */
  fsPath: string;

  /**
   * Name is the file or directory name
   */
  fsName: string;

  /**
   * Partial content of file, only including lines of `paragraph`.
   */
  content?: string;

  /**
   * Lines range in the file.
   */
  paragraph: [start: number, end: number];

  /**
   * Content summary generated by Agent.
   */
  summary: string;

  /**
   * Does the content is embedded and stored into Vector database?
   */
  isEmbedded: boolean;
}
